version: "3"
services:

  postgres:
    container_name: lintang-postgres
    image: postgres:14-alpine
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2000mb
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'lintang' # awalnya postgres
    ports:
      - 5431:5432


  pg-admin:
    image: dpage/pgadmin4:8
    deploy:
      resources:
        limits:
          cpus: '0.6'
          memory: 600mb
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - PGADMIN_LISTEN_PORT=5050
    volumes:
      -  pgadmin-data:/var/lib/pgadmin
    ports:
      - 5053:5050

  user-service:
      container_name: user-service
      build:
        context: .
        dockerfile: Dockerfile
      mem_limit: 300mb
      volumes:
        - ./cert:/cert
      cpus: 0.5
      ports:
        - 9995:9995

  
volumes:
  pg-data:
  pgadmin-data: